### ISSUE TITLE
Switch from Selenium to crawler4j

### ISSUE THREAD

**Issue by colatkinson** [LMSGrabber/LMSGrabber#60]
As Moorthy noted, web crawling is an essentially solved problem. Instead of implementing this ourselves, it is likely simpler to use [yasserg/crawler4j](https://github.com/yasserg/crawler4j).

**Comment by colatkinson** [comment]
Crawler4j only works on static content. Probably should have realized this would cause problems before starting work on this. :sunglasses: :gun:

**Comment by ghost** [comment]
R.I.P.
